### PR TITLE
Compile doc tests and fix resulting errors

### PR DESCRIPTION
**Pull request by Fraser999**

### CODE REVIEW

**Comment by seladb** [comment]
Conflicts again :)

**Comment by seladb** [comment]
btw, do you have more changes coming?

If not I can publish a new version with the changes you've made

**Comment by Fraser999** [comment]
That's all the changes I have.  Thanks for merging them all :)  Publishing a new version would be appreciated.

**Comment by seladb** [comment]
Sure. Could you please summarize the changes you've done? I'll put them in the release notes

**Comment by Fraser999** [comment]
Sure:

* Changed all doc tests from `ignore` to `no_run` so generated docs don't contain untested warnings
* Changed both instances of `lextend` to take iterators of references rather than a slice of values
* Fixed bug in `load_test()`
* Fixed rustfmt and clippy warnings
* Added examples to Cargo.toml to allow them to be run via cargo

**Comment by seladb** [comment]
I've published a new version (0.4.0). Thank you for all your help! You've made a substantial contribution to this library and I really appreciate your efforts. 

Please let me know if you have more ideas for new features or additional improvements you'd like to add

**Comment by Fraser999** [comment]
No problem :)  Thanks for being responsive and publishing the new version so quickly.

**Comment by seladb** [comment]
BTW if you like this project please feel free to add a Github star :)

You can also share it with you friends and ask them to add Github stars too.

That way we can get more visibility for this project which will help us to make it better.

**Pull request merged**
