### PR TITLE
Addition of Nanoserde backend for smaller dependency tree and faster compile

### PR DESCRIPTION
**Pull request by knickish**
Wanted to use pickleDB, but trying to avoid having quote + syn in my build tree. This change optionally reduces the number of deps for the library to one, with similar performance to bincode according to the test suite.

### CODE REVIEW

**Comment by knickish** [comment]
Fixed the clippy workflow to work with the new combinations and ran rustfmt

**Comment by knickish** [comment]
Any interest in merging this or should I just use my fork?

**Comment by seladb** [comment]
@knickish I'm sorry for the late reply.

There are a lot of changes in this PR and it's not easy to review all of them. Any chance of splitting into smaller PRs?

**Comment by knickish** [comment]
@seladb Sure, will see what I can do about making it smaller this weekend.

**Comment by knickish** [comment]
@seladb

**Comment by knickish** [comment]
Closed in light of discussion in #31

**Pull request closed without merging**
